#!/bin/bash

# source ./apiAutomation-0x00

# pokemons=$(jq -r '.results[]["name"]' data.json)
POKEMONS=[ "bulbasaur", "ivysaur", "venusaur", "charmander", "charmeleon" ]

for POKEMON in "${POKEMONS[@]}"; do
    echo "Fetching data for $POKEMON"
    OUTPUT_FILE="./pokemon_data/$POKEMON.json"
    source ./apiAutomation-0x00
done
